### ISSUE TITLE
Duplicate containers created

### ISSUE THREAD

**Issue by itzoke** [tomaskir/NetXMS-csv-importer#4]
While importing a CSV file with 239 hosts and container creation enabled I ended up with one or more duplicate containers with one node in them.

part of CSV-file
```
lar-T01-cV01,xxx.yyy.zzz.71,Larvik
lar-T01-cO01,xxx.yyy.zzz.72,Larvik
lar-T01-cV02,xxx.yyy.zzz.73,Larvik
lar-T01-cO02,xxx.yyy.zzz.74,Larvik
lar-T02-cV01,xxx.yyy.zzz.75,Larvik
lar-T02-cO01,xxx.yyy.zzz.76,Larvik
lar-T02-cV02,xxx.yyy.zzz.77,Larvik
lar-T02-cO02,xxx.yyy.zzz.78,Larvik
lar-T03-cV01,xxx.yyy.zzz.79,Larvik
lar-T03-cV02,xxx.yyy.zzz.80,Larvik
lar-T03-cN01,xxx.yyy.zzz.81,Larvik
```
Result: 
![image](https://user-images.githubusercontent.com/15806657/89695493-7690dd00-d914-11ea-8110-3abba442b6f5.png)

Duplicate containers were created for every site. Even the ones with only two nodes.

Server version: 3.4-284
csv-importer built from src against newest client library
```
diff --git a/pom.xml b/pom.xml
index ca19712..5f7d92c 100644
--- a/pom.xml
+++ b/pom.xml
@@ -6,14 +6,14 @@
 
     <groupId>com.github.tomaskir</groupId>
     <artifactId>netxms-csv-importer</artifactId>
-    <version>1.1.3</version>
+    <version>1.1.4</version>
     <packaging>jar</packaging>
 
     <properties>
         <source.encoding>utf-8</source.encoding>
         <java.version>1.7</java.version>
         <lombok.version>1.16.10</lombok.version>
-        <netxms-client.version>3.0.2258</netxms-client.version>
+        <netxms-client.version>3.4.187</netxms-client.version>
     </properties>
 
     <dependencies>
```

**Comment by itzoke** [comment]
There are never more than three duplicate containers.

By the looks of it, it seems that for the first three nodes added we're not getting a container object back from `nxcSession.findObject(filter);`. For the remaining nodes however we get the object (not necessarily the first container created).

![image](https://user-images.githubusercontent.com/15806657/89696322-a5f51900-d917-11ea-8d1d-7bcfd16f2133.png)
Container and node names prefixed with object ID to shed some light on what's happening.

**Comment by tomaskir** [comment]
Fixed in latest release, containers are now created synchronously (new feature in latest NetXMS client lib), node creation still async for better speed of import.
