### ISSUE TITLE
Incompatible with latest server version

### ISSUE THREAD

**Issue by martinyelland** [tomaskir/NetXMS-csv-importer#5]
Connecting to the NetXMS server.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Error: NXCException - Server uses incompatible version of communication protocol (server=[60, 4, 1, 1, 1, 41, 1, 2] client=[53, 4, 1, 1, 1, 29, 1, 2])

**Comment by tomaskir** [comment]
A new version with support for latest NetXMS version was just released.
